import { useEffect, useState } from 'react';
import toast from 'react-hot-toast';
import { casinoCatalogClient } from '../services/casinoCatalogClient';
import { useCasinoStore } from '../state/casinoStore';
export default function CasinoCatalogPage() {
  const [games, setGames] = useState<any[]>([]); const [category, setCategory] = useState('ALL'); const [launch, setLaunch] = useState<any>(null); const [loading, setLoading] = useState(false); const setBalance = useCasinoStore(state => state.setBalance);
  useEffect(() => { casinoCatalogClient.games().then(data => setGames(data.games)).catch(error => toast.error(error.response?.data?.error || 'Catalog unavailable')); }, []);
  const visible = category === 'ALL' ? games : games.filter(game => game.kind === category);
  const open = async (game: any) => { setLoading(true); try { setLaunch((await casinoCatalogClient.launch(game.gameId)).launch); } catch (error: any) { toast.error(error.response?.data?.error || error.message); } finally { setLoading(false); } };
  const wager = async () => { if (!launch) return; setLoading(true); try { const data = await casinoCatalogClient.wager({ wagerId: crypto.randomUUID(), sessionId: launch.sessionId, stakeSol: 0.001 }); setBalance(data.newBalance); toast.success(`Provider result: ${data.wager.outcome}`); } catch (error: any) { toast.error(error.response?.data?.error || error.message); } finally { setLoading(false); } };
  return <main className="px-4 py-8"><div className="flex justify-between items-center mb-6"><div><h1 className="text-3xl font-black">CASINO CATALOG</h1><p className="text-xs text-gray-500">External games · provider-owned outcomes · unified ledger</p></div><div className="flex gap-2"><button onClick={() => setCategory('ALL')} className="px-3 py-2 rounded bg-blue-600 text-xs">ALL</button><button onClick={() => setCategory('SLOT')} className="px-3 py-2 rounded bg-[#172533] text-xs">SLOTS</button><button onClick={() => setCategory('LIVE_CASINO')} className="px-3 py-2 rounded bg-[#172533] text-xs">LIVE CASINO</button></div></div><div className="grid md:grid-cols-2 lg:grid-cols-4 gap-4">{visible.map(game => <article key={game.gameId} className="rounded-2xl bg-[#101b27] border border-white/10 p-5"><div className="text-4xl mb-4">{game.kind === 'SLOT' ? '🎰' : '🃏'}</div><h2 className="font-black">{game.name}</h2><p className="text-xs text-gray-500">{game.studio} · {game.category}</p><button disabled={loading} onClick={() => open(game)} className="mt-5 w-full rounded-lg bg-blue-600 py-2 font-bold disabled:bg-gray-700">OPEN GAME</button></article>)}</div>{launch && <div className="fixed inset-0 bg-black/80 flex items-center justify-center p-4"><div className="bg-[#101b27] rounded-2xl p-6 max-w-sm w-full"><h2 className="font-black text-xl">{launch.gameId}</h2><p className="text-sm text-gray-400 mt-2">Sandbox provider session active. Test wager: 0.001 SOL.</p><button disabled={loading} onClick={wager} className="mt-5 w-full rounded-lg bg-emerald-600 py-3 font-bold">PLACE TEST WAGER</button><button onClick={() => setLaunch(null)} className="mt-2 w-full rounded-lg bg-gray-700 py-2">CLOSE</button></div></div>}</main>;
}
